downloads_dir: D:\Project\teleg\Arachne\downloads
max_concurrent_downloads: '3'
log_level: INFO
proxy_enabled: false
proxy_url: socks5://127.0.0.1:1080
use_aria2: false
limit_rate: '0'
save_thumbnail: true
embed_thumbnail: true
embed_chapters: true
embed_subtitles: false
auto_download_after_analyse: false
batch_download_quality: 1080p
batch_download_format: mp4
